### ISSUE TITLE
Missed lines color doesn't work for color blind people

### ISSUE THREAD

**Issue by edimossilva** [simplecov-ruby/simplecov-html#105] opened 2020-09-30 06:47 UTC
This color doesn't work for color blind people.

https://github.com/simplecov-ruby/simplecov-html/blob/3a30b47964e74ac810edc02629d420fa1cb1bc12/assets/stylesheets/screen.css#L287

**Comment by PragTob** [comment] 2020-10-18 19:00
Duplicate of https://github.com/simplecov-ruby/simplecov/issues/534

**Closed by PragTob** 2020-10-18 19:00 UTC
